default:
	javac *.java

run:
	java Main

clean:
	rm -f *.class
	clear
	reset
	clear

tar:
	rm -f *.tar.gz
	tar -cvz SkipListNode.java SkipList.java -f uXXXXXXX_Practical_1.tar.gz

untar:
	tar -zxvf *.tar.gz