default:
	javac *.java

run:
	java Main

clean:
	rm -f *.class
	reset
	clear

tar:
	rm -f *.class *.tar.gz
	tar -cvz Edge.java Graph.java Vertex.java -f Graph.tar.gz

unzip:
	tar -zxvf *.tar