default:
	javac *.java

run:
	java App

clean:
	rm -f *.class *.tar.gz
	clear
	reset
	clear

tar:
	rm -f *.tar.gz
	tar -cvz Traverser.java IterativeTraverse.java RecursiveTraverse.java SelfOrderingList.java CountList.java MoveToFrontList.java NaturalOrderList.java TransposeList.java Node.java -f uXXXXXXXX_Practical_2.tar.gz

untar:
	tar -zxvf *.tar.gz